# Generated by Django 4.2.4 on 2023-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
